---
- name: Install main redis package
  package:
    name: redis
    state: present

- name: Install php redis package
  package:
    name: php-pecl-redis5
    state: present

#- name: Copy main redis.conf
#  copy: 
#    src: files/redis.conf 
#    dest: /etc/redis.conf
#    owner: redis
#    group: redis
#  register: redis_conf

- name: Ensure redis is running
  service:
    name: redis
    state: restarted
    enabled: true
  when: redis_conf.changed
