- hosts: krabice.tomaso.cz

  roles:
  - common
  - certbot
#  - backup
  - geerlingguy.apache
#  - grafana
#  - influxdb
#  - iptables
  - firewalld
  - mirror
#  - redis
#  - telegraf
#  - weldpua2008.hugo

- hosts: tomaso.cz

  roles:
    - common
    - certbot
    - transmission

- hosts: nuc.tomaso.cz

  roles:
    - common

- hosts: 
    - knode1.tomaso.cz
    - knode2.tomaso.cz
    - knode3.tomaso.cz
    - knode4.tomaso.cz
    - knode5.tomaso.cz

  roles:
    - k8s_playground

- hosts: rpi1.kouba.xyz
  roles:
    - certbot
    - deconz
    - hass
    - geerlingguy.apache
    - procmail
    - postfix
