- hosts: krabice.tomaso.cz

  roles:
  - common
  - certbot
  - backup
  - geerlingguy.apache
  - grafana
  - influxdb
  - telegraf
#  - weldpua2008.hugo

- hosts: tomaso.cz

  roles:
    - common
    - certbot
    - transmission
