---
bb_account_id: "{{ vault_bb_account_id }}"
bb_app_key: "{{ vault_bb_app_key }}"
bb_bucket: "krabice-backup"
bb_bucket_dir: "nextcloud_data"
gpg_passphrase: "{{ vault_gpg_passphrase }}"


certbot_domains: 
  - gogs.tomaso.cz
  - gotour.tomaso.cz
  - grafana.tomaso.cz
  - krabice.tomaso.cz
  - jp.tomaso.cz
  - mb.tomaso.cz
  - nc.tomaso.cz

apache_daemon: httpd-prefork
apache_vhosts_version: "2.4"
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

iptables_save_file: "krabice.iptables.saved"
ip6tables_save_file: "krabice.ip6tables.saved"
