---
bb_account_id: "{{ vault_bb_account_id }}"
bb_app_key: "{{ vault_bb_app_key }}"
bb_bucket: "krabice-backup"
bb_bucket_dir: "nextcloud_data"
gpg_passphrase: "{{ vault_gpg_passphrase }}"


certbot_domains: 
  - gogs.tomaso.cz
  - grafana.tomaso.cz
  - jp.tomaso.cz
  - krabice.tomaso.cz
  - mb.tomaso.cz
  - nc.tomaso.cz

apache_daemon: httpd-prefork
apache_vhosts_version: "2.4"
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443
apache_vhosts_ssl:
  - servername: "grafana.tomaso.cz"
    documentroot: "/srv/www/htdocs/grafana"
    certificate_file: "/etc/certbot/live/grafana.tomaso.cz/cert.pem"
    certificate_key_file: "/etc/certbot/live/grafana.tomaso.cz/privkey.pem"
    certificate_chain_file: "/etc/certbot/live/grafana.tomaso.cz/fullchain.pem"
    extra_parameters: |
      ProxyPass / http://localhost:3001/
      ProxyPassReverse / http://localhost:3001/

