---
- name: Copy iptables.save to /tmp
  copy: src=files/{{ iptables_save_file }} dest=/tmp/iptables.save
  register: iptables_save

- name: Load iptables rules from a file
  command: /usr/sbin/iptables-restore /tmp/iptables.save
  when: iptables_save.changed

- name: Copy ip6tables.save to /tmp
  copy: src=files/{{ ip6tables_save_file }} dest=/tmp/ip6tables.save
  register: ip6tables_save

- name: Load ip6tables rules from a file
  command: /usr/sbin/ip6tables-restore /tmp/ip6tables.save
  when: ip6tables_save.changed
