---

- name: Check base repo stat
  stat: path=/etc/yum.repos.d/CentOS-Base.repo
  register: base_repo_stat

- name: Disable official base repo
  command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.disabled
  when: base_repo_stat.stat.exists

- rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

- name: Setup local mirror (1/3)
  yum_repository:
    name: base
    description: CentOS - Base
    baseurl: http://10.8.100.1:8080/centos/$releasever/os/$basearch/
    gpgcheck: true
    gpgcakey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: true

- name: Setup local mirror (2/3)
  yum_repository:
    name: updates
    description: CentOS - Updates
    baseurl: http://10.8.100.1:8080/centos/$releasever/updates/$basearch/
    gpgcheck: true
    gpgcakey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: true

- name: Setup local mirror (3/3)
  yum_repository:
    name: extras
    description: CentOS - Extras
    baseurl: http://10.8.100.1:8080/centos/$releasever/extras/$basearch/
    gpgcheck: true
    gpgcakey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    enabled: true

- name: Install useful admin tools
  package: 
    name:
      - git
      - mc
      - nmap
      - telnet
      - net-tools
      - strace
      - vim-enhanced
      - bind-utils
      - lsof
      - bridge-utils
    state: latest

- name: "RedHat | Add yum repository"
  yum_repository:
    name: kubernetes
    description: Kubernetes google repo - CentOS $releasever
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el{{ ansible_distribution_major_version }}-x86_64"
    gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  register: kubernetes_repo_present

- name: Install kubernetes packages
  package: 
    name:
      - docker
      - kubectl
      - kubeadm
      - kubelet
    state: latest
  when: kubernetes_repo_present is succeeded

- name: Stop and disable firewall on VMs
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Start kubelet service
  service:
    name: kubelet
    state: started
    enabled: true

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: true

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
