---

- name: Install certbot scripts
  package: 
    name: python3-certbot
    state: latest

- name: Configure certbot template
  template:
    src: templates/certbot-cli.ini
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Certbot renewal cronjob
  cron:
    name: certbot renewal
    weekday: '6'
    minute: '9'
    hour: '9'
    user: 'root'
    job: "systemctl stop {{ apache_service }}; /usr/bin/certbot -n certonly --config /etc/letsencrypt/cli.ini; systemctl start {{ apache_service }}"
    cron_file: ansible_cerbot-renewal

